/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 用户注册 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        /** @description 注册成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        409: components["responses"]["Conflict"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 用户登录 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description 登录成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 刷新 Access Token */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description 长期有效的刷新令牌 */
            refresh_token: string;
          };
        };
      };
      responses: {
        /** @description 刷新成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 退出登录 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 退出成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SimpleSuccessResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取当前用户信息 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UserInfoResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取对话历史 */
    get: {
      parameters: {
        query: {
          project_id: string;
          /** @description 页码（从1开始） */
          page?: components["parameters"]["PageParam"];
          /** @description 每页数量 */
          limit?: components["parameters"]["LimitParam"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GetMessagesResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    put?: never;
    /** 发送消息 */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SendMessageRequest"];
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SendMessageResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/voice": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 语音消息输入
     * @description 上传语音文件，系统将自动识别并转换为文本消息
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "multipart/form-data": {
            /**
             * Format: binary
             * @description 音频文件（支持 wav, mp3, m4a, ogg）
             */
            audio: string;
            /** @description 项目 ID */
            project_id: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["VoiceMessageResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 上传参考文件 */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            file: string;
            project_id: string;
          };
        };
      };
      responses: {
        /** @description 上传成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UploadResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/files/{file_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 删除上传的文件 */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          file_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 删除成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SimpleSuccessResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/files/{file_id}/intent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 标注文件用途 */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          file_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateFileIntentRequest"];
        };
      };
      responses: {
        /** @description 标注成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UpdateFileIntentResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    trace?: never;
  };
  "/api/v1/files/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 批量上传文件
     * @description 一次上传多个参考文件
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "multipart/form-data": {
            /** @description 多个文件 */
            files: string[];
            project_id: string;
          };
        };
      };
      responses: {
        /** @description 批量上传成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BatchUploadResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /** 批量删除文件 */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description 要删除的文件 ID 列表 */
            file_ids: string[];
          };
        };
      };
      responses: {
        /** @description 批量删除成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BatchDeleteResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/courseware": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 生成课件（兼容入口）
     * @description 兼容旧版的一次性创建接口。新流程推荐使用 /generate/sessions 系列接口，
     *     支持阶段式中断、事件流推送与局部重绘。
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
          /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
          "X-Contract-Version"?: components["parameters"]["ContractVersion"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["GenerateRequest"];
        };
      };
      responses: {
        /** @description 生成任务已创建 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GenerateResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 创建生成会话
     * @description 创建可中断、可恢复的课件生成会话（契约优先主入口）
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
          /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
          "X-Contract-Version"?: components["parameters"]["ContractVersion"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateGenerationSessionRequest"];
        };
      };
      responses: {
        /** @description 会话创建成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CreateGenerationSessionResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/sessions/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询生成会话快照 */
    get: {
      parameters: {
        query?: never;
        header?: {
          /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
          "X-Contract-Version"?: components["parameters"]["ContractVersion"];
        };
        path: {
          session_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GenerationSessionResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/sessions/{session_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 获取生成事件流（SSE）
     * @description 默认返回 text/event-stream。当客户端无法使用 SSE 时，可通过 `accept=application/json`
     *     返回短轮询事件列表。
     */
    get: {
      parameters: {
        query?: {
          /** @description 事件游标（用于断线续传） */
          cursor?: string;
          accept?: "text/event-stream" | "application/json";
        };
        header?: {
          /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
          "X-Contract-Version"?: components["parameters"]["ContractVersion"];
        };
        path: {
          session_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": string;
            "application/json": components["schemas"]["GenerationEventListResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/sessions/{session_id}/outline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 更新大纲并回写会话
     * @deprecated
     * @description 兼容别名，等价于 command_type=UPDATE_OUTLINE
     */
    put: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
          /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
          "X-Contract-Version"?: components["parameters"]["ContractVersion"];
        };
        path: {
          session_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateOutlineRequest"];
        };
      };
      responses: {
        /** @description 大纲更新成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UpdateOutlineResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["Conflict"];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/sessions/{session_id}/commands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 执行会话命令（唯一写入口）
     * @description 所有会引起状态变化或内容变化的操作统一通过 Command 接口执行。
     *     服务层必须通过统一状态转换校验器（StateTransitionGuard）决定是否允许执行。
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
          /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
          "X-Contract-Version"?: components["parameters"]["ContractVersion"];
        };
        path: {
          session_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["GenerationSessionCommandRequest"];
        };
      };
      responses: {
        /** @description 命令已执行或接受 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GenerationSessionCommandResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["Conflict"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/sessions/{session_id}/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 确认大纲并继续生成
     * @deprecated
     * @description 兼容别名，等价于 command_type=CONFIRM_OUTLINE
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
          /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
          "X-Contract-Version"?: components["parameters"]["ContractVersion"];
        };
        path: {
          session_id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ConfirmOutlineRequest"];
        };
      };
      responses: {
        /** @description 已进入内容生成 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ConfirmOutlineResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["Conflict"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/sessions/{session_id}/outline/redraft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 请求 AI 重写大纲
     * @deprecated
     * @description 兼容别名，等价于 command_type=REDRAFT_OUTLINE
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
          /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
          "X-Contract-Version"?: components["parameters"]["ContractVersion"];
        };
        path: {
          session_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RedraftOutlineRequest"];
        };
      };
      responses: {
        /** @description 已进入大纲重写阶段 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["RedraftOutlineResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["Conflict"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/sessions/{session_id}/resume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 恢复中断会话
     * @deprecated
     * @description 兼容别名，等价于 command_type=RESUME_SESSION
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
          "X-Contract-Version"?: components["parameters"]["ContractVersion"];
        };
        path: {
          session_id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ResumeSessionRequest"];
        };
      };
      responses: {
        /** @description 恢复成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ResumeSessionResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["Conflict"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/sessions/{session_id}/slides/{slide_id}/regenerate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 局部重绘单页
     * @deprecated
     * @description 兼容别名，等价于 command_type=REGENERATE_SLIDE
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
          /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
          "X-Contract-Version"?: components["parameters"]["ContractVersion"];
        };
        path: {
          session_id: string;
          slide_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegenerateSlideRequest"];
        };
      };
      responses: {
        /** @description 局部重绘成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["RegenerateSlideResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["Conflict"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 获取生成域能力声明
     * @description 返回服务端当前支持的契约版本、特性开关与弃用信息。
     */
    get: {
      parameters: {
        query?: never;
        header?: {
          /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
          "X-Contract-Version"?: components["parameters"]["ContractVersion"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GenerationCapabilitiesResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/tasks/{task_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询生成状态 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          task_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GenerateStatusResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/tasks/{task_id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 下载生成的课件文件 */
    get: {
      parameters: {
        query: {
          /** @description 要下载的文件类型 */
          file_type: "ppt" | "word";
        };
        header?: never;
        path: {
          task_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 文件下载成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/vnd.openxmlformats-officedocument.presentationml.presentation": string;
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/generate/tasks/{task_id}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取任务的所有版本 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          task_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["VersionsResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/preview/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取课件预览 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          task_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PreviewResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/preview/{task_id}/modify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 提交修改指令 */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
        };
        path: {
          task_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ModifyRequest"];
        };
      };
      responses: {
        /** @description 修改任务已创建 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ModifyResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/preview/{task_id}/slides/{slide_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 获取单个幻灯片详情
     * @description 查看特定幻灯片的详细内容和来源
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          task_id: string;
          slide_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SlideDetailResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/preview/{task_id}/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 导出预览内容
     * @description 将预览内容导出为指定格式
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          task_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * @description 导出格式
             * @enum {string}
             */
            format: "json" | "markdown" | "html";
            /**
             * @description 是否包含来源信息
             * @default true
             */
            include_sources?: boolean;
          };
        };
      };
      responses: {
        /** @description 导出成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              success?: boolean;
              data?: {
                /** @description 导出的内容 */
                content?: string;
                format?: string;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rag/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 检索知识库 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RAGSearchRequest"];
        };
      };
      responses: {
        /** @description 检索成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["RAGSearchResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rag/sources/{chunk_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查看来源详情 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          chunk_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SourceDetailResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rag/index": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 索引新文件到知识库
     * @description 将上传的文件添加到 RAG 知识库索引
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description 要索引的文件 ID */
            file_id: string;
            /**
             * @description 分块大小
             * @default 512
             */
            chunk_size?: number;
            /**
             * @description 分块重叠大小
             * @default 50
             */
            chunk_overlap?: number;
          };
        };
      };
      responses: {
        /** @description 索引任务已创建 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              success?: boolean;
              data?: {
                index_task_id?: string;
                /** @enum {string} */
                status?: "pending" | "processing" | "completed" | "failed";
              };
            };
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rag/similar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 查找相似内容
     * @description 基于给定文本查找知识库中的相似内容
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description 要查找相似内容的文本 */
            text: string;
            /** @default 5 */
            top_k?: number;
            /**
             * Format: float
             * @description 相似度阈值
             * @default 0.7
             */
            threshold?: number;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["RAGSearchResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取项目列表 */
    get: {
      parameters: {
        query?: {
          /** @description 页码（从1开始） */
          page?: components["parameters"]["PageParam"];
          /** @description 每页数量 */
          limit?: components["parameters"]["LimitParam"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GetProjectsResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    /** 创建项目 */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ProjectRequest"];
        };
      };
      responses: {
        /** @description 项目创建成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ProjectResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取项目详情 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          project_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ProjectResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    /** 修改项目信息 */
    put: {
      parameters: {
        query?: never;
        header?: {
          /** @description 幂等性密钥，用于防止重复请求。 */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
        };
        path: {
          project_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ProjectRequest"];
        };
      };
      responses: {
        /** @description 更新成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ProjectResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    post?: never;
    /** 删除项目 */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          project_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 删除成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SimpleSuccessResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{project_id}/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取项目的上传文件列表 */
    get: {
      parameters: {
        query?: {
          /** @description 页码（从1开始） */
          page?: components["parameters"]["PageParam"];
          /** @description 每页数量 */
          limit?: components["parameters"]["LimitParam"];
        };
        header?: never;
        path: {
          project_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GetFilesResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{project_id}/statistics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 获取项目统计信息
     * @description 获取项目的文件数、对话数、生成任务数等统计信息
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          project_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ProjectStatisticsResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 搜索项目
     * @description 根据关键词搜索项目
     */
    get: {
      parameters: {
        query: {
          /** @description 搜索关键词 */
          q: string;
          /** @description 按状态筛选 */
          status?: "draft" | "in_progress" | "completed";
          /** @description 页码（从1开始） */
          page?: components["parameters"]["PageParam"];
          /** @description 每页数量 */
          limit?: components["parameters"]["LimitParam"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GetProjectsResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /**
       * Format: password
       * @example SecurePass123
       */
      password: string;
      /** @example john_doe */
      username: string;
      /** @example John Doe */
      fullName?: string;
    };
    UserInfo: {
      id: string;
      /** Format: email */
      email: string;
      username: string;
      fullName?: string;
      /** Format: date-time */
      createdAt: string;
    };
    AuthResponse: {
      success: boolean;
      data: {
        access_token?: string;
        refresh_token?: string;
        expires_in?: number;
        user?: components["schemas"]["UserInfo"];
      };
      message: string;
    };
    ErrorResponse: {
      /** @example false */
      success: boolean;
      error: {
        code: string;
        message: string;
        /** @description 是否建议客户端重试 */
        retryable?: boolean;
        /** @description 结构化错误详情（例如字段错误、状态冲突上下文） */
        details?: {
          [key: string]: unknown;
        };
        /** @description 服务端追踪 ID，用于日志排障 */
        trace_id?: string;
      };
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    SimpleSuccessResponse: {
      /** @example true */
      success: boolean;
      /** @example 操作成功 */
      message: string;
    };
    UserInfoResponse: {
      success: boolean;
      data: {
        user?: components["schemas"]["UserInfo"];
      };
      message: string;
    };
    SourceReference: {
      /** @description 来源片段唯一标识，可用于查询来源详情 */
      chunk_id: string;
      /** @enum {string} */
      source_type: "video" | "document" | "ai_generated";
      filename: string;
      page_number?: number;
      timestamp?: string;
      preview_text?: string;
    };
    Message: {
      id: string;
      /** @enum {string} */
      role: "user" | "assistant" | "system";
      content: string;
      /** Format: date-time */
      timestamp: string;
      /** @description assistant 回复关联的来源引用（可选，建议尽量返回） */
      citations?: components["schemas"]["SourceReference"][];
    };
    GetMessagesResponse: {
      success: boolean;
      data: {
        messages?: components["schemas"]["Message"][];
        total?: number;
        page?: number;
        limit?: number;
      };
      message: string;
    };
    SendMessageRequest: {
      project_id: string;
      content: string;
      history?: components["schemas"]["Message"][];
    };
    SendMessageResponse: {
      success: boolean;
      data: {
        message?: components["schemas"]["Message"];
        suggestions?: string[];
      };
      message: string;
    };
    VoiceMessageResponse: {
      success: boolean;
      data: {
        /** @description 识别的文本内容 */
        text?: string;
        /**
         * Format: float
         * @description 识别置信度
         */
        confidence?: number;
        /**
         * Format: float
         * @description 音频时长（秒）
         */
        duration?: number;
        /** @description 自动创建的消息对象 */
        message?: components["schemas"]["Message"];
        /** @description AI 建议 */
        suggestions?: string[];
      };
      message: string;
    };
    UploadedFile: {
      id: string;
      filename: string;
      /** @enum {string} */
      file_type: "pdf" | "word" | "video" | "image" | "ppt";
      mime_type?: string;
      /** @description File size in bytes. Maximum allowed size is 100MB (104857600 bytes). */
      file_size: number;
      /** @enum {string} */
      status: "uploading" | "parsing" | "ready" | "failed";
      /** @description 解析进度百分比 */
      parse_progress?: number;
      /** @description 解析详情 */
      parse_details?: {
        /** @description 提取的页数 */
        pages_extracted?: number;
        /** @description 提取的图片数 */
        images_extracted?: number;
        /** @description 提取的文本长度 */
        text_length?: number;
        /** @description 视频时长（秒） */
        duration?: number;
      };
      /** @description 解析错误信息 */
      parse_error?: string;
      /** @description 文件用途说明 */
      usage_intent?: string;
      /** @description 解析结果摘要 */
      parse_result?: Record<string, never>;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at?: string;
    };
    UploadResponse: {
      success: boolean;
      data: {
        file?: components["schemas"]["UploadedFile"];
      };
      message: string;
    };
    UpdateFileIntentRequest: {
      usage_intent: string;
    };
    UpdateFileIntentResponse: {
      success: boolean;
      data: {
        file?: components["schemas"]["UploadedFile"];
      };
      message: string;
    };
    BatchUploadResponse: {
      success: boolean;
      data: {
        files?: components["schemas"]["UploadedFile"][];
        /** @description 成功上传的文件数 */
        total?: number;
        /** @description 上传失败的文件列表 */
        failed?: {
          filename?: string;
          error?: string;
        }[];
      };
      message: string;
    };
    BatchDeleteResponse: {
      success: boolean;
      data: {
        /** @description 成功删除的文件数 */
        deleted?: number;
        /** @description 删除失败的文件列表 */
        failed?: {
          file_id?: string;
          error?: string;
        }[];
      };
      message: string;
    };
    /** @enum {string} */
    GenerationSessionMode: "ppt" | "word" | "both";
    /** @enum {string} */
    CoursewareStylePreset: "academic" | "vibrant" | "dark_tech" | "custom";
    /** @enum {string} */
    GenerationAudience: "beginner" | "intermediate" | "professional";
    GenerationOptions: {
      /**
       * @description PPT 模板风格
       * @default default
       * @enum {string}
       */
      template: "default" | "gaia" | "uncover" | "academic";
      style_preset?: components["schemas"]["CoursewareStylePreset"];
      /**
       * @description 主题色（十六进制颜色代码）
       * @example #4A90E2
       */
      theme_color?: string;
      /**
       * @description 是否显示页码
       * @default true
       */
      show_page_number: boolean;
      /** @description 页眉文本 */
      header?: string;
      /** @description 页脚文本 */
      footer?: string;
      /** @description 期望的页数 */
      pages?: number;
      audience?: components["schemas"]["GenerationAudience"];
      target_duration_minutes?: number;
      /**
       * @description 是否生成动画创意
       * @default false
       */
      include_animations: boolean;
      /**
       * @description 是否生成互动游戏
       * @default false
       */
      include_games: boolean;
      /**
       * @description 动画输出格式（当 include_animations 为 true 时）
       * @enum {string}
       */
      animation_format?: "gif" | "mp4" | "html5";
      /**
       * @description 是否启用自动配图
       * @default false
       */
      use_text_to_image: boolean;
      /** @description 用户输入的主基调 Prompt */
      system_prompt_tone?: string;
      /** @description 本次生成绑定的素材 ID 列表 */
      rag_source_ids?: string[];
    };
    GenerateRequest: {
      project_id: string;
      type: components["schemas"]["GenerationSessionMode"];
      options?: components["schemas"]["GenerationOptions"];
      /**
       * @description 兼容旧入口时可直接生成，推荐先走大纲确认
       * @default draft_then_confirm
       * @enum {string}
       */
      start_mode: "direct_generate" | "draft_then_confirm";
      /** @description 客户端会话 ID，用于断线重连恢复 */
      client_session_id?: string;
    };
    /** @enum {string} */
    GenerateTaskStatus: "pending" | "processing" | "completed" | "failed";
    /** @enum {string} */
    GenerationState:
      | "IDLE"
      | "CONFIGURING"
      | "ANALYZING"
      | "DRAFTING_OUTLINE"
      | "AWAITING_OUTLINE_CONFIRM"
      | "GENERATING_CONTENT"
      | "RENDERING"
      | "SUCCESS"
      | "FAILED";
    GenerateResponse: {
      success: boolean;
      data: {
        task_id?: string;
        session_id?: string;
        status?: components["schemas"]["GenerateTaskStatus"];
        state?: components["schemas"]["GenerationState"];
      };
      message: string;
    };
    CreateGenerationSessionRequest: {
      project_id: string;
      output_type: components["schemas"]["GenerationSessionMode"];
      options?: components["schemas"]["GenerationOptions"];
      client_session_id?: string;
    };
    SessionRef: {
      session_id: string;
      project_id: string;
      /** @description 兼容旧任务模型时可返回 */
      task_id?: string;
      state: components["schemas"]["GenerationState"];
      /** @description 状态附加语义（用于未知状态或灰度状态说明） */
      state_reason?: string;
      status?: components["schemas"]["GenerateTaskStatus"];
      /** @example 2026-03 */
      contract_version: string;
      /** @description 会话载荷结构版本 */
      schema_version?: number;
      progress?: number;
      resumable?: boolean;
      /** Format: date-time */
      updated_at?: string;
    };
    CreateGenerationSessionResponse: {
      success: boolean;
      data: {
        session: components["schemas"]["SessionRef"];
      };
      message: string;
    };
    OutlineNode: {
      id: string;
      order: number;
      title: string;
      key_points?: string[];
      slide_hint?: string;
      estimated_minutes?: number;
    };
    OutlineDocument: {
      version: number;
      nodes: components["schemas"]["OutlineNode"][];
      summary?: string;
    };
    SessionContextSnapshot: {
      retrieval_id?: string;
      selected_source_ids?: string[];
      notes?: string;
    };
    /** @enum {string} */
    CapabilityStatus: "available" | "degraded" | "unavailable";
    CapabilityDeclaration: {
      /** @enum {string} */
      name:
        | "document_parser"
        | "video_understanding"
        | "speech_recognition"
        | "outline_generation"
        | "slide_regeneration"
        | "event_stream";
      status: components["schemas"]["CapabilityStatus"];
      providers?: string[];
      default_provider?: string;
      fallback_chain?: string[];
      operations: string[];
      status_message?: string;
    };
    ExternalFallbackInfo: {
      /** @enum {string} */
      capability:
        | "document_parser"
        | "video_understanding"
        | "speech_recognition";
      /**
       * @description 原始目标能力或供应商
       * @example MinerU
       */
      provider?: string;
      fallback_used: boolean;
      /**
       * @description 实际回退到的能力或供应商
       * @example local_parser
       */
      fallback_target?: string;
      /**
       * @description 降级原因码（超时/限流/服务不可用等）
       * @example PROVIDER_TIMEOUT
       */
      reason_code?: string;
      /** @description 可直接展示给用户的降级提示语 */
      user_message?: string;
    };
    SessionStatePayload: {
      session: components["schemas"]["SessionRef"];
      options?: components["schemas"]["GenerationOptions"];
      outline?: components["schemas"]["OutlineDocument"];
      context_snapshot?: components["schemas"]["SessionContextSnapshot"];
      /** @description 服务端能力声明（状态、供应商、可用操作） */
      capabilities?: components["schemas"]["CapabilityDeclaration"][];
      /** @description 当前会话发生过的能力降级记录（按时间追加） */
      fallbacks?: components["schemas"]["ExternalFallbackInfo"][];
      /** @description 当前状态下允许的下一步动作（防止前后端状态错配） */
      allowed_actions?: string[];
      result?: {
        ppt_url?: string;
        word_url?: string;
        version?: number;
      };
      error?: {
        code?: string;
        message?: string;
        retryable?: boolean;
        fallback?: components["schemas"]["ExternalFallbackInfo"];
        /**
         * @description 状态转换校验器名称
         * @example StateTransitionGuard
         */
        transition_guard?: string;
      };
    };
    GenerationSessionResponse: {
      success: boolean;
      data: components["schemas"]["SessionStatePayload"];
      message: string;
    };
    /** @enum {string} */
    GenerationEventType:
      | "state.changed"
      | "progress.updated"
      | "outline.ready"
      | "outline.updated"
      | "slide.updated"
      | "task.completed"
      | "task.failed"
      | "session.recovered";
    GenerationEvent: {
      event_id: string;
      /** @default 1 */
      event_schema_version: number;
      event_type: components["schemas"]["GenerationEventType"];
      state: components["schemas"]["GenerationState"];
      state_reason?: string;
      progress?: number;
      /** Format: date-time */
      timestamp: string;
      /** @description 增量消费游标 */
      cursor: string;
      /** @description 事件附带的业务数据 */
      payload?: Record<string, never>;
    };
    GenerationEventListResponse: {
      success: boolean;
      data: {
        events?: components["schemas"]["GenerationEvent"][];
      };
      message: string;
    };
    UpdateOutlineRequest: {
      /** @description 客户端编辑所基于的大纲版本（并发控制） */
      base_version: number;
      outline: components["schemas"]["OutlineDocument"];
      change_reason?: string;
    };
    UpdateOutlineResponse: {
      success: boolean;
      data: {
        session?: components["schemas"]["SessionRef"];
        outline?: components["schemas"]["OutlineDocument"];
      };
      message: string;
    };
    UpdateOutlineCommand: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      command_type: "UpdateOutlineCommand";
      base_version: number;
      outline: components["schemas"]["OutlineDocument"];
      change_reason?: string;
    };
    RedraftOutlineCommand: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      command_type: "RedraftOutlineCommand";
      instruction: string;
      base_version: number;
    };
    ConfirmOutlineCommand: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      command_type: "ConfirmOutlineCommand";
      /** @default true */
      continue_from_retrieval: boolean;
      expected_state?: components["schemas"]["GenerationState"];
    };
    /** @enum {string} */
    StructuredPatchOperationType:
      | "replace_text"
      | "insert_block"
      | "remove_block"
      | "replace_image"
      | "reorder_block";
    StructuredSlidePatchOperation: {
      op: components["schemas"]["StructuredPatchOperationType"];
      /**
       * @description 目标路径（JSON Pointer 风格）
       * @example /slides/5/body/blocks/2
       */
      path: string;
      /** @description 操作值（按 op 类型解释） */
      value?: Record<string, never>;
      /** @description 可选备注，便于审计与回放 */
      note?: string;
    };
    StructuredSlidePatch: {
      /** @default 1 */
      schema_version: number;
      operations: components["schemas"]["StructuredSlidePatchOperation"][];
    };
    RegenerateSlideCommand: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      command_type: "RegenerateSlideCommand";
      slide_id: string;
      patch: components["schemas"]["StructuredSlidePatch"];
      expected_render_version?: number;
    };
    ResumeSessionCommand: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      command_type: "ResumeSessionCommand";
      cursor?: string;
      last_known_state?: components["schemas"]["GenerationState"];
    };
    GenerationCommandEnvelope:
      | components["schemas"]["UpdateOutlineCommand"]
      | components["schemas"]["RedraftOutlineCommand"]
      | components["schemas"]["ConfirmOutlineCommand"]
      | components["schemas"]["RegenerateSlideCommand"]
      | components["schemas"]["ResumeSessionCommand"];
    GenerationSessionCommandRequest: {
      command: components["schemas"]["GenerationCommandEnvelope"];
    };
    /** @enum {string} */
    GenerationCommandType:
      | "UPDATE_OUTLINE"
      | "REDRAFT_OUTLINE"
      | "CONFIRM_OUTLINE"
      | "REGENERATE_SLIDE"
      | "RESUME_SESSION";
    AppliedTransition: {
      command_type: components["schemas"]["GenerationCommandType"];
      from_state: components["schemas"]["GenerationState"];
      to_state: components["schemas"]["GenerationState"];
      /** @example StateTransitionGuard */
      validated_by: string;
    };
    GenerationSessionCommandResponse: {
      success: boolean;
      data: {
        command_id: string;
        /** @default true */
        accepted: boolean;
        transition?: components["schemas"]["AppliedTransition"];
        session: components["schemas"]["SessionRef"];
        warnings?: string[];
      };
      message: string;
    };
    ConfirmOutlineRequest: {
      /**
       * @description 是否复用 ANALYZING 阶段上下文
       * @default true
       */
      continue_from_retrieval: boolean;
      /** @description 乐观并发控制，默认应为 AWAITING_OUTLINE_CONFIRM */
      expected_state?: components["schemas"]["GenerationState"];
    };
    ConfirmOutlineResponse: {
      success: boolean;
      data: {
        session?: components["schemas"]["SessionRef"];
      };
      message: string;
    };
    RedraftOutlineRequest: {
      /** @description 用户要求重写大纲的指导语 */
      instruction: string;
      /** @description 当前确认页所见大纲版本 */
      base_version: number;
    };
    RedraftOutlineResponse: {
      success: boolean;
      data: {
        session?: components["schemas"]["SessionRef"];
      };
      message: string;
    };
    ResumeSessionRequest: {
      /** @description 上次消费到的事件游标 */
      cursor?: string;
      last_known_state?: components["schemas"]["GenerationState"];
    };
    ResumeSessionResponse: {
      success: boolean;
      data: {
        session?: components["schemas"]["SessionRef"];
        latest_event?: components["schemas"]["GenerationEvent"];
      };
      message: string;
    };
    RegenerateSlideRequest: {
      /** @description 可选自然语言补充说明，最终以结构化 patch 为准 */
      instruction?: string;
      slide_index?: number;
      patch: components["schemas"]["StructuredSlidePatch"];
      /** @description 防止并发覆盖的版本控制字段 */
      expected_render_version?: number;
    };
    RegenerateSlideResponse: {
      success: boolean;
      data: {
        session?: components["schemas"]["SessionRef"];
        updated_slide?: {
          slide_id?: string;
          slide_index?: number;
          content_markdown?: string;
          sources?: components["schemas"]["SourceReference"][];
          render_version?: number;
        };
      };
      message: string;
    };
    StateTransitionRule: {
      command_type: components["schemas"]["GenerationCommandType"];
      from_state: components["schemas"]["GenerationState"];
      to_state: components["schemas"]["GenerationState"];
    };
    StateMachineDeclaration: {
      states: components["schemas"]["GenerationState"][];
      terminal_states: components["schemas"]["GenerationState"][];
      transitions: components["schemas"]["StateTransitionRule"][];
    };
    GenerationCapabilitiesResponse: {
      success: boolean;
      data: {
        contract_versions: string[];
        default_contract_version: string;
        command_interface: {
          /** @example /api/v1/generate/sessions/{session_id}/commands */
          endpoint: string;
          supported_commands: components["schemas"]["GenerationCommandType"][];
        };
        capabilities: components["schemas"]["CapabilityDeclaration"][];
        state_machine: components["schemas"]["StateMachineDeclaration"];
        deprecations?: {
          api?: string;
          /** Format: date-time */
          sunset_at?: string;
          replacement?: string;
        }[];
      };
      message: string;
    };
    GenerateStatusResponse: {
      success: boolean;
      data: {
        task_id?: string;
        session_id?: string;
        status?: components["schemas"]["GenerateTaskStatus"];
        state?: components["schemas"]["GenerationState"];
        /** @description 生成进度百分比 */
        progress?: number;
        outline?: components["schemas"]["OutlineDocument"];
        result?: {
          ppt_url?: string;
          word_url?: string;
          /** @description 当前版本号 */
          version?: number;
        };
        error?: string;
        error_detail?: {
          code?: string;
          message?: string;
          retryable?: boolean;
        };
      };
      message: string;
    };
    VersionsResponse: {
      success: boolean;
      data: {
        task_id?: string;
        versions?: {
          version?: number;
          /** Format: date-time */
          created_at?: string;
          /** @enum {string} */
          status?: "completed" | "failed";
          file_urls?: {
            ppt_url?: string;
            word_url?: string;
          };
          /** @description 修改说明 */
          modification_note?: string;
        }[];
      };
      message: string;
    };
    Slide: {
      id: string;
      index: number;
      title: string;
      content: string;
      sources: components["schemas"]["SourceReference"][];
      thumbnail_url?: string;
    };
    SlidePlan: {
      slide_id: string;
      teaching_goal: string;
      teacher_script: string;
      teaching_suggestions?: string[];
      suggested_duration?: number;
      material_sources?: components["schemas"]["SourceReference"][];
    };
    LessonPlan: {
      teaching_objectives?: string[];
      slides_plan?: components["schemas"]["SlidePlan"][];
    };
    PreviewResponse: {
      success: boolean;
      data: {
        task_id?: string;
        slides?: components["schemas"]["Slide"][];
        lesson_plan?: components["schemas"]["LessonPlan"];
      };
      message: string;
    };
    ModifyRequest: {
      instruction: string;
      target_slides?: string[];
      context?: Record<string, never>;
    };
    ModifyResponse: {
      success: boolean;
      data: {
        modify_task_id?: string;
        /** @enum {string} */
        status?: "pending" | "processing" | "completed" | "failed";
      };
      message: string;
    };
    SlideDetailResponse: {
      success: boolean;
      data: {
        slide?: components["schemas"]["Slide"];
        /** @description 该幻灯片对应的教学计划 */
        teaching_plan?: components["schemas"]["SlidePlan"];
        /** @description 相关幻灯片 */
        related_slides?: {
          slide_id?: string;
          title?: string;
          /** @enum {string} */
          relation?: "previous" | "next" | "related";
        }[];
      };
      message: string;
    };
    RAGSearchRequest: {
      project_id: string;
      query: string;
      /** @default 5 */
      top_k: number;
      filters?: {
        file_types?: ("pdf" | "word" | "video" | "image" | "ppt")[];
        file_ids?: string[];
      };
    };
    RAGResult: {
      chunk_id: string;
      content: string;
      /** Format: float */
      score: number;
      source: components["schemas"]["SourceReference"];
      metadata?: Record<string, never>;
    };
    RAGSearchResponse: {
      success: boolean;
      data: {
        results?: components["schemas"]["RAGResult"][];
        total?: number;
      };
      message: string;
    };
    SourceDetailResponse: {
      success: boolean;
      data: {
        chunk_id?: string;
        content?: string;
        source?: components["schemas"]["SourceReference"];
        context?: {
          previous_chunk?: string;
          next_chunk?: string;
        };
        file_info?: components["schemas"]["UploadedFile"];
      };
      message: string;
    };
    Project: {
      id: string;
      name: string;
      description: string;
      grade_level?: string;
      /** @enum {string} */
      status: "draft" | "in_progress" | "completed";
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    GetProjectsResponse: {
      success: boolean;
      data: {
        projects?: components["schemas"]["Project"][];
        total?: number;
        page?: number;
        limit?: number;
      };
      message: string;
    };
    ProjectRequest: {
      name: string;
      description: string;
      grade_level?: string;
    };
    ProjectResponse: {
      success: boolean;
      data: {
        project?: components["schemas"]["Project"];
      };
      message: string;
    };
    GetFilesResponse: {
      success: boolean;
      data: {
        files?: components["schemas"]["UploadedFile"][];
        total?: number;
        page?: number;
        limit?: number;
      };
      message: string;
    };
    ProjectStatisticsResponse: {
      success: boolean;
      data: {
        project_id?: string;
        /** @description 上传的文件数 */
        files_count?: number;
        /** @description 对话消息数 */
        messages_count?: number;
        /** @description 生成任务数 */
        generation_tasks_count?: number;
        /** @description 已完成的任务数 */
        completed_tasks_count?: number;
        /** @description 文件总大小（字节） */
        total_file_size?: number;
        /**
         * Format: date-time
         * @description 最后活动时间
         */
        last_activity?: string;
        /** Format: date-time */
        created_at?: string;
      };
      message: string;
    };
  };
  responses: {
    /** @description 请求参数错误或验证失败 */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description 资源冲突 */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description 未认证或 Token 无效/过期 */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description 无权限访问此资源 */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description 请求的资源不存在 */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    /** @description 页码（从1开始） */
    PageParam: number;
    /** @description 每页数量 */
    LimitParam: number;
    /** @description 幂等性密钥，用于防止重复请求。 */
    IdempotencyKey: string;
    /** @description 客户端期望的契约版本；服务端可据此做兼容降级与告警。 */
    ContractVersion: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
