services:
  ourograph:
    image: spectra-ourograph:dev
    build:
      context: ./ourograph
      dockerfile: Dockerfile.dev
    environment:
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx1024m -XX:MaxMetaspaceSize=256m
    healthcheck:
      start_period: 180s
    volumes:
      - ./ourograph:/app
      - runtime_data:/var/lib/spectra
