from __future__ import annotations

import re
from pathlib import Path

from .models import DocumentProfile

HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
PREFIX_RE = re.compile(r"^\d+(?:\.\d+)*\.?\s*")
MERMAID_BLOCK_RE = re.compile(r"```mermaid\s*\n.*?\n```", re.DOTALL)


def strip_heading_prefix(text: str) -> str:
    return PREFIX_RE.sub("", text).strip()


def sanitize_mermaid(text: str, placeholder_text: str) -> str:
    return MERMAID_BLOCK_RE.sub(placeholder_text, text)


def build_header(profile: DocumentProfile, extra_meta: dict | None = None) -> str:
    meta = {"title": profile.title, "lang": profile.lang}
    if extra_meta:
        meta.update({key: value for key, value in extra_meta.items() if value is not None})
    lines = ["---"]
    for key, value in meta.items():
        escaped = str(value).replace('"', '\\"')
        lines.append(f'{key}: "{escaped}"')
    lines.append("---")
    lines.append("")
    lines.append("<!-- Generated by personal-doc-engine. Edit source chapters, not this merged file. -->")
    return "\n".join(lines)


def renumber_markdown(text: str, chapter_no: int, placeholder_text: str) -> str:
    sec = 0
    sub = 0
    output: list[str] = []
    for line in text.lstrip("\ufeff").splitlines():
        match = HEADING_RE.match(line)
        if not match:
            output.append(line)
            continue
        hashes, raw_title = match.groups()
        title = strip_heading_prefix(raw_title)
        level = len(hashes)
        if level == 1:
            sec = 0
            sub = 0
            output.append(f"# {chapter_no}. {title}")
        elif level == 2:
            sec += 1
            sub = 0
            output.append(f"## {chapter_no}.{sec} {title}")
        elif level == 3:
            if sec == 0:
                sec = 1
            sub += 1
            output.append(f"### {chapter_no}.{sec}.{sub} {title}")
        else:
            output.append(line)
    return sanitize_mermaid("\n".join(output).strip(), placeholder_text)


def build_merged_markdown(
    markdown_files: list[Path],
    profile: DocumentProfile,
    exec_summary_file: Path | None = None,
    extra_meta: dict | None = None,
) -> str:
    parts = [build_header(profile, extra_meta=extra_meta).strip()]
    if exec_summary_file and profile.include_exec_summary:
        exec_text = exec_summary_file.read_text(encoding="utf-8")
        parts.append(sanitize_mermaid(exec_text.strip(), profile.figure_placeholder_text))
    for index, chapter_path in enumerate(markdown_files, start=profile.body_starts_at):
        parts.append("[[PAGEBREAK]]")
        chapter_text = chapter_path.read_text(encoding="utf-8")
        parts.append(
            renumber_markdown(
                chapter_text,
                chapter_no=index + profile.body_chapter_offset,
                placeholder_text=profile.figure_placeholder_text,
            )
        )
    return "\n\n".join(parts).strip() + "\n"
