#!/usr/bin/env python3
"""Build a draft PostgreSQL Prisma baseline package without mutating live migrations."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Callable, Mapping

try:
    from scripts._script_bootstrap import ensure_backend_import_path
except ModuleNotFoundError:
    from _script_bootstrap import ensure_backend_import_path

ensure_backend_import_path()

from scripts import postgres_baseline_diff as baseline_diff  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_PACKAGE_ROOT = ROOT / "backend/prisma/postgres-baseline-package"
DEFAULT_MIGRATION_TAG = "00000000000000_postgres_baseline"


def build_baseline_package(
    env: Mapping[str, str],
    *,
    package_root: Path = DEFAULT_PACKAGE_ROOT,
    migration_tag: str = DEFAULT_MIGRATION_TAG,
    schema_output: Path = baseline_diff.DEFAULT_SCHEMA_OUTPUT,
    run_diff: Callable[..., tuple[list[str], int]] = baseline_diff.render_baseline_diff,
) -> tuple[list[str], int]:
    messages = ["PostgreSQL baseline package"]
    baseline_dir = package_root / "migrations" / migration_tag
    baseline_sql = baseline_dir / "migration.sql"
    lock_file = package_root / "migrations" / "migration_lock.toml"

    diff_messages, diff_exit = run_diff(
        env,
        schema_output=schema_output,
        output_path=baseline_sql,
    )
    messages.extend(f"[diff] {message}" for message in diff_messages[1:])
    if diff_exit != 0:
        return messages, diff_exit

    baseline_dir.mkdir(parents=True, exist_ok=True)
    lock_file.parent.mkdir(parents=True, exist_ok=True)
    lock_file.write_text(
        "# Please do not edit this file manually\n"
        "# Draft PostgreSQL baseline generated for cutover preparation\n"
        'provider = "postgresql"\n',
        encoding="utf-8",
    )
    (package_root / "README.md").write_text(
        (
            "# PostgreSQL Baseline Package\n\n"
            "This directory is a generated draft used to prepare the PostgreSQL "
            "cutover baseline.\n"
            "Review the SQL and migration lock before promoting it into live "
            "Prisma migrations.\n"
        ),
        encoding="utf-8",
    )
    messages.append(f"PASS wrote draft migration lock to {lock_file}")
    messages.append(f"PASS wrote draft baseline migration to {baseline_sql}")
    return messages, 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_PACKAGE_ROOT,
        help=(
            "Directory where the draft PostgreSQL baseline package " "should be built."
        ),
    )
    parser.add_argument(
        "--migration-tag",
        default=DEFAULT_MIGRATION_TAG,
        help="Directory name to use for the generated baseline migration.",
    )
    parser.add_argument(
        "--run",
        action="store_true",
        help=(
            "Generate the PostgreSQL baseline package instead of "
            "only printing intent."
        ),
    )
    args = parser.parse_args()

    print("PostgreSQL baseline package")
    print(f"output_dir={args.output_dir}")
    print(f"migration_tag={args.migration_tag}")

    if not args.run:
        print("Dry run only. Re-run with --run to generate the baseline package.")
        return 0

    messages, exit_code = build_baseline_package(
        {},
        package_root=args.output_dir,
        migration_tag=args.migration_tag,
    )
    for message in messages:
        print(message)
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
