import type { AnimationScene } from "./types";

interface BuildCodeParams {
  topic: string;
  scene: AnimationScene;
  speed: number;
  showTrail: boolean;
  lineColor: string;
}

function sceneRuntimeName(scene: AnimationScene): string {
  if (scene === "bubble_sort") return "bubbleSortScene";
  if (scene === "magnetic_field") return "magneticFieldScene";
  return "particleOrbitScene";
}

function sceneLabel(scene: AnimationScene): string {
  if (scene === "bubble_sort") return "冒泡排序动画";
  if (scene === "magnetic_field") return "磁感线变化";
  return "粒子公转演示";
}

export function buildAnimationCode({
  topic,
  scene,
  speed,
  showTrail,
  lineColor,
}: BuildCodeParams): string {
  return [
    "const config = {",
    `  topic: "${topic.trim() || "本节知识点"}",`,
    `  scene: "${sceneRuntimeName(scene)}",`,
    `  speed: ${Number((speed / 100).toFixed(2))},`,
    `  showTrail: ${showTrail},`,
    `  lineColor: "${lineColor}",`,
    "};",
    "",
    "renderAnimation(config);",
    "",
    "function renderAnimation(input) {",
    "  // TODO: generated by animation card",
    "  // 1) init scene  2) loop frame  3) update visual state",
    "}",
  ].join("\n");
}

export function buildAnimationDescription(scene: AnimationScene): string {
  return `当前场景：${sceneLabel(scene)}。可在预览里调速度和轨迹颜色。`;
}
