from __future__ import annotations

from schemas.studio_cards import (
    StudioCardBindingStatus,
    StudioCardExecutionBinding,
    StudioCardExecutionPlan,
    StudioCardReadiness,
    StudioCardTransport,
)

CARD_EXECUTION_PLANS: dict[str, StudioCardExecutionPlan] = {
    "courseware_ppt": StudioCardExecutionPlan(
        card_id="courseware_ppt",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.SESSION_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/generate/sessions",
            required_fields=["project_id", "output_type", "bootstrap_only"],
            bound_config_keys=[
                "output_type",
                "bootstrap_only",
                "topic",
                "pages",
                "target_slide_count",
                "generation_mode",
                "template_id",
                "style_preset",
                "visual_policy",
                "rag_source_ids",
            ],
            pending_config_keys=[],
            result_fields=["session.session_id", "session.output_type"],
            notes="课件卡片已接入 create-session bootstrap 绑定链，正式生成由 Diego runtime 承担。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            bound_config_keys=["card_id"],
            pending_config_keys=["selection_anchor", "slide_scope"],
            result_fields=["message", "citations"],
            notes="课件微调先承托到 chat 通道，单页定向 patch 仍由生成主链局部修改协议负责。",
        ),
    ),
    "word_document": StudioCardExecutionPlan(
        card_id="word_document",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility", "source_artifact_id"],
            bound_config_keys=[
                "type",
                "source_artifact_id",
                "document_variant",
                "teaching_model",
                "grade_band",
                "difficulty_layer",
            ],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="文档卡片改为 artifact create 主路径，细分配置通过 content 正式绑定。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/generate/studio-cards/{card_id}/refine",
            required_fields=["project_id", "artifact_id", "message"],
            bound_config_keys=["selection_anchor", "document_content"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="文档 block 级编辑与 replacement artifact 已通过 structured refine 收口。",
        ),
    ),
    "interactive_quick_quiz": StudioCardExecutionPlan(
        card_id="interactive_quick_quiz",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=[
                "type",
                "question_count",
                "difficulty",
                "humorous_distractors",
            ],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="exercise artifact 已可创建，题量/难度等配置现在通过 content 正式绑定。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/generate/studio-cards/{card_id}/refine",
            required_fields=["project_id", "artifact_id", "message"],
            bound_config_keys=["current_question_id"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="单题级改写已通过 refine replacement artifact 正式收口。",
        ),
    ),
    "knowledge_mindmap": StudioCardExecutionPlan(
        card_id="knowledge_mindmap",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=["type", "focus_scope"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="mindmap artifact 已具备，聚焦范围现在通过 content 正式绑定。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/generate/studio-cards/{card_id}/refine",
            required_fields=["project_id", "artifact_id", "message"],
            bound_config_keys=["selected_node_path"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="节点选中后的导图扩展已通过 refine replacement artifact 正式收口。",
        ),
    ),
    "demonstration_animations": StudioCardExecutionPlan(
        card_id="demonstration_animations",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=[
                "type",
                "animation_format",
                "motion_brief",
                "scene",
                "speed",
                "show_trail",
                "split_view",
                "line_color",
            ],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="动画生成以 animation_storyboard artifact 为正式输入，可正式输出 HTML5、GIF 与 MP4 成果。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/generate/studio-cards/{card_id}/refine",
            required_fields=["project_id", "artifact_id"],
            bound_config_keys=[
                "duration_seconds",
                "rhythm",
                "style_pack",
                "visual_type",
                "focus",
                "render_mode",
            ],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="动画正式 refine 已收口为 structured_refine replacement artifact；chat 仅保留为策略控制面。",
        ),
        source_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_REFERENCE,
            status=StudioCardBindingStatus.READY,
            method="GET",
            endpoint="/api/v1/generate/studio-cards/{card_id}/sources",
            required_fields=["project_id"],
            result_fields=["sources", "source_binding_candidates"],
            notes="PPT source-binding 用于 placement 二阶段，不是动画生成前提。",
        ),
        placement_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_REFERENCE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/generate/studio-cards/{card_id}/confirm-placement",
            required_fields=["project_id", "artifact_id", "ppt_artifact_id", "page_numbers", "slot"],
            bound_config_keys=["ppt_artifact_id", "page_numbers", "slot"],
            pending_config_keys=["placement_ready_artifact"],
            result_fields=["artifact.id", "ppt_artifact.id", "placements"],
            notes="placement 是动画卡正式二阶段动作；当前仅当动画成果满足可投放前提时可闭环写入 PPT 绑定关系。",
        ),
    ),
    "interactive_games": StudioCardExecutionPlan(
        card_id="interactive_games",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=["type", "game_pattern", "creative_brief"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="HTML artifact 是当前正式载体，但实际 payload 仍经 legacy compatibility 层收口，属于冻结清理区而非 fully ready runtime。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/generate/studio-cards/{card_id}/refine",
            required_fields=["project_id", "artifact_id"],
            bound_config_keys=["sandbox_patch"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="refine 仍走 replacement HTML artifact，但当前 rewrite 由 legacy compatibility adapter 承托，需以前端 protocol-limited 语义显式展示。",
        ),
    ),
    "speaker_notes": StudioCardExecutionPlan(
        card_id="speaker_notes",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility", "source_artifact_id"],
            bound_config_keys=[
                "type",
                "source_artifact_id",
                "topic",
                "tone",
                "emphasize_interaction",
            ],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="说课助手当前通过 summary artifact 正式承托逐页讲稿生成。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/generate/studio-cards/{card_id}/refine",
            required_fields=["project_id", "artifact_id", "message"],
            bound_config_keys=["source_artifact_id", "selected_script_segment"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="提词器段落级改写已通过 refine replacement artifact 正式收口。",
        ),
        source_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_REFERENCE,
            status=StudioCardBindingStatus.READY,
            method="GET",
            endpoint="/api/v1/generate/studio-cards/{card_id}/sources",
            required_fields=["project_id", "artifact_id"],
            result_fields=["artifact.id", "artifact.type", "artifact.metadata"],
            notes="PPT artifact 候选已可通过 card source-binding 协议正式获取。",
        ),
    ),
    "classroom_qa_simulator": StudioCardExecutionPlan(
        card_id="classroom_qa_simulator",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=["type", "student_profiles", "question_focus", "turns"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="学情预演以 summary artifact 承托预演脚本，并作为 turn 协议的稳定输入。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=[],
            bound_config_keys=["active_student_profile", "turn_anchor"],
            result_fields=["message", "citations"],
            notes="整体追问风格调整继续通过 chat 承托；正式多轮推进由 turn 协议负责。",
        ),
        follow_up_turn_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_REFERENCE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/generate/studio-cards/classroom_qa_simulator/turn",
            required_fields=["project_id", "artifact_id", "teacher_answer"],
            bound_config_keys=["turn_anchor", "active_student_profile"],
            result_fields=["turn_result", "artifact.id"],
            notes="多轮追问已通过 turn 接口正式收口，并以 replace artifact 持续演进。",
        ),
    ),
}
