from __future__ import annotations

from schemas.studio_cards import (
    StudioCardBindingStatus,
    StudioCardExecutionBinding,
    StudioCardExecutionPlan,
    StudioCardReadiness,
    StudioCardTransport,
)

CARD_EXECUTION_PLANS: dict[str, StudioCardExecutionPlan] = {
    "word_document": StudioCardExecutionPlan(
        card_id="word_document",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.SESSION_CREATE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/generate/sessions",
            required_fields=["project_id", "output_type"],
            bound_config_keys=["output_type"],
            pending_config_keys=["document_variant", "teaching_model", "grade_band"],
            result_fields=["session.session_id", "session.output_type"],
            notes="create-session 主路径已稳定，文档细分配置尚未绑定到正式请求体。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            bound_config_keys=["card_id"],
            pending_config_keys=["selection_anchor", "artifact_span"],
            result_fields=["message", "citations"],
            notes="卡片上下文对话已具备，但局部文档改写锚点协议仍待补齐。",
        ),
    ),
    "interactive_quick_quiz": StudioCardExecutionPlan(
        card_id="interactive_quick_quiz",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/project-space/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=["type"],
            pending_config_keys=[
                "question_count",
                "difficulty",
                "humorous_distractors",
            ],
            result_fields=["artifact.id", "artifact.type"],
            notes="exercise artifact 已可创建，但题量/难度等配置还未绑定到正式生成 payload。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=["current_question_id"],
            result_fields=["message", "citations"],
            notes="题目上下文改写已可承托，单题闪卡协议仍待补齐。",
        ),
    ),
    "knowledge_mindmap": StudioCardExecutionPlan(
        card_id="knowledge_mindmap",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/project-space/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=["type"],
            pending_config_keys=["focus_scope"],
            result_fields=["artifact.id", "artifact.type"],
            notes="mindmap artifact 已具备，聚焦范围与上下文绑定仍待补齐。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=["selected_node_path"],
            result_fields=["message", "citations"],
            notes="节点选中态扩展方向明确，但节点级 patch 协议尚未正式建模。",
        ),
    ),
    "demonstration_animations": StudioCardExecutionPlan(
        card_id="demonstration_animations",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/project-space/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=["type"],
            pending_config_keys=["animation_format", "motion_brief"],
            result_fields=["artifact.id", "artifact.type"],
            notes="gif/mp4/html artifact 已可承载，参数化动画生成语义仍待补齐。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=["animation_parameters"],
            result_fields=["message", "citations"],
            notes="动画热更新方向已明确，但参数级重载协议尚未收口。",
        ),
    ),
    "interactive_games": StudioCardExecutionPlan(
        card_id="interactive_games",
        readiness=StudioCardReadiness.PROTOCOL_PENDING,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.PENDING,
            method="POST",
            endpoint="/api/v1/project-space/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=["type"],
            pending_config_keys=["game_pattern", "creative_brief"],
            result_fields=["artifact.id", "artifact.type"],
            notes="HTML artifact 容器已具备，游戏专用生成协议仍未落地。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PENDING,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=["sandbox_patch"],
            result_fields=["message"],
            notes="热更新方向明确，但 sandbox patch 协议仍待正式建模。",
        ),
    ),
    "speaker_notes": StudioCardExecutionPlan(
        card_id="speaker_notes",
        readiness=StudioCardReadiness.PROTOCOL_PENDING,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.SESSION_CREATE,
            status=StudioCardBindingStatus.PENDING,
            method="POST",
            endpoint="/api/v1/generate/sessions",
            required_fields=["project_id", "output_type"],
            bound_config_keys=["output_type"],
            pending_config_keys=["source_artifact_id"],
            result_fields=["session.session_id"],
            notes="说课助手仍依赖 PPT/source artifact 的组合语义，尚未拥有独立生成协议。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PENDING,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=["selected_script_segment"],
            result_fields=["message"],
            notes="段落级改写是目标能力，但卡片专用提词器协议仍待建模。",
        ),
        source_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_REFERENCE,
            status=StudioCardBindingStatus.PARTIAL,
            method="GET",
            endpoint="/api/v1/project-space/{project_id}/artifacts/{artifact_id}",
            required_fields=["project_id", "artifact_id"],
            result_fields=["artifact.id", "artifact.type", "artifact.metadata"],
            notes="PPT artifact 读取已经存在，但说课助手如何消费该 artifact 仍待正式绑定。",
        ),
    ),
    "classroom_qa_simulator": StudioCardExecutionPlan(
        card_id="classroom_qa_simulator",
        readiness=StudioCardReadiness.PROTOCOL_PENDING,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PENDING,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=["student_profiles", "question_focus"],
            result_fields=["message", "citations"],
            notes="学情预演主要承托在 chat/session/rag 组合语义上，专用模拟协议仍待落地。",
        ),
    ),
}
