from __future__ import annotations

from schemas.studio_cards import (
    StudioCardBindingStatus,
    StudioCardExecutionBinding,
    StudioCardExecutionPlan,
    StudioCardReadiness,
    StudioCardTransport,
)

CARD_EXECUTION_PLANS: dict[str, StudioCardExecutionPlan] = {
    "word_document": StudioCardExecutionPlan(
        card_id="word_document",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.SESSION_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/generate/sessions",
            required_fields=["project_id", "output_type"],
            bound_config_keys=[
                "output_type",
                "document_variant",
                "teaching_model",
                "grade_band",
            ],
            pending_config_keys=[],
            result_fields=["session.session_id", "session.output_type"],
            notes="create-session 主路径已稳定，文档细分配置通过 options 正式绑定。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            bound_config_keys=["card_id"],
            pending_config_keys=["selection_anchor", "artifact_span"],
            result_fields=["message", "citations"],
            notes="卡片上下文对话已具备，但局部文档改写锚点协议仍待补齐。",
        ),
    ),
    "interactive_quick_quiz": StudioCardExecutionPlan(
        card_id="interactive_quick_quiz",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=[
                "type",
                "question_count",
                "difficulty",
                "humorous_distractors",
            ],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="exercise artifact 已可创建，题量/难度等配置现在通过 content 正式绑定。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=["current_question_id"],
            result_fields=["message", "citations"],
            notes="题目上下文改写已可承托，单题闪卡协议仍待补齐。",
        ),
    ),
    "knowledge_mindmap": StudioCardExecutionPlan(
        card_id="knowledge_mindmap",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=["type", "focus_scope"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="mindmap artifact 已具备，聚焦范围现在通过 content 正式绑定。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=["selected_node_path"],
            result_fields=["message", "citations"],
            notes="节点选中态扩展方向明确，但节点级 patch 协议尚未正式建模。",
        ),
    ),
    "demonstration_animations": StudioCardExecutionPlan(
        card_id="demonstration_animations",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=["type", "animation_format", "motion_brief"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="gif/mp4/html artifact 已可承载，动画格式与描述现在通过 content 正式绑定。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=["animation_parameters"],
            result_fields=["message", "citations"],
            notes="动画热更新方向已明确，但参数级重载协议尚未收口。",
        ),
    ),
    "interactive_games": StudioCardExecutionPlan(
        card_id="interactive_games",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=["type", "game_pattern", "creative_brief"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="HTML artifact 已可承托互动游戏原型，初始配置通过 content 正式绑定。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=["sandbox_patch"],
            result_fields=["message"],
            notes="热更新方向明确，但 sandbox patch 协议仍待正式建模。",
        ),
    ),
    "speaker_notes": StudioCardExecutionPlan(
        card_id="speaker_notes",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.SESSION_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/generate/sessions",
            required_fields=["project_id", "output_type"],
            bound_config_keys=["output_type", "source_artifact_id"],
            pending_config_keys=[],
            result_fields=["session.session_id"],
            notes="说课助手当前通过 source-artifact + create-session 正式承托初始执行。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            bound_config_keys=["source_artifact_id"],
            pending_config_keys=["selected_script_segment"],
            result_fields=["message", "citations"],
            notes="提词器段落改写已能承托到 chat，对段落锚点的正式协议仍待补齐。",
        ),
        source_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_REFERENCE,
            status=StudioCardBindingStatus.READY,
            method="GET",
            endpoint="/api/v1/generate/studio-cards/{card_id}/sources",
            required_fields=["project_id", "artifact_id"],
            result_fields=["artifact.id", "artifact.type", "artifact.metadata"],
            notes="PPT artifact 候选已可通过 card source-binding 协议正式获取。",
        ),
    ),
    "classroom_qa_simulator": StudioCardExecutionPlan(
        card_id="classroom_qa_simulator",
        readiness=StudioCardReadiness.FOUNDATION_READY,
        initial_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.ARTIFACT_CREATE,
            status=StudioCardBindingStatus.READY,
            method="POST",
            endpoint="/api/v1/projects/{project_id}/artifacts",
            required_fields=["project_id", "type", "visibility"],
            bound_config_keys=["type", "student_profiles", "question_focus", "turns"],
            pending_config_keys=[],
            result_fields=["artifact.id", "artifact.type"],
            notes="学情预演当前先以 summary artifact 承托预演脚本，后续再接虚拟问答回路。",
        ),
        refine_binding=StudioCardExecutionBinding(
            transport=StudioCardTransport.CHAT_MESSAGE,
            status=StudioCardBindingStatus.PARTIAL,
            method="POST",
            endpoint="/api/v1/chat/messages",
            required_fields=["project_id", "message"],
            pending_config_keys=["active_student_profile", "turn_anchor"],
            result_fields=["message", "citations"],
            notes="教师追问风格调整已可承托到 chat，虚拟学生多轮模拟协议仍待补齐。",
        ),
    ),
}
